services:
  channel-service-postgres:
    image: postgres:16-alpine
    container_name: pg-channel-service
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: channel_db
    volumes:
      - pgdata1:/var/lib/postgresql/data
    restart: unless-stopped
  channel-service:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: channel-app
    ports:
      - "8080:8080"    # HTTP Spring Boot
      - "9090:9090"    # gRPC
    depends_on:
      - channel-service-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://channel-service-postgres:5432/channel_db
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
    restart: unless-stopped
    networks:
      - streaming-platform

volumes:
  pgdata1:

networks:
  streaming-platform:
    external: true
  pgdata1: