services:
  stream-service-postgres:
    image: postgres:16-alpine
    container_name: pg-stream-service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: stream_db
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata2: