services:
  stream-service-postgres:
    image: postgres:16-alpine
    container_name: pg-stream-service
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: stream_db
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: unless-stopped
  
  stream-service:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: stream-app
    ports:
      - "8081:8081"
    depends_on:
      - stream-service-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stream-service-postgres:5432/stream_db
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
    restart: unless-stopped

volumes:
  pgdata2: